[package]
name = "vec3_class"
version = "0.1.0"
edition = "2018"

[dependencies.rand]
version = "0.7.3"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
